# Generated by Django 3.1.5 on 2021-01-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='아이디')),
                ('userpasswword', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('useremail', models.EmailField(max_length=128, verbose_name='이메일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='수정일시')),
            ],
        ),
    ]
