# Generated by Django 3.1.5 on 2021-01-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='userpasswword',
            new_name='userpassword',
        ),
    ]
